theme: jekyll-theme-minimal
logo: /assets/img/kundera_dog.jpeg
title: Viscerally ambiguous workspace of MoonSoo Choi
description: `A safe, clopen space for creative expressions`
show_downloads: False
navigation:
  - title: about
    url: /
#  - title: setup
#    url: setup
  - title: writings (novellas)
    url: writings
  - title: blogs
    url: blogs
  - title: '>  data science blogs'
    url: blogs-ds
  - title: '>  being vs. doing'
    url: blogs-work
comments:
  provider: "staticman"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
