theme: jekyll-theme-minimal
title: Viscerally ambiguous blog of M.S. Choi
description: Work and creative space of M.S. Choi
show_downloads: False
navigation:
  - title: home
    url: /
  - title: setup
    url: setup
  - title: blog
    url: /blog
